config.reload.automatic: true
config.reload.interval: 10s
http.host: 0.0.0.0
pipeline.workers: 1
path.config: /usr/share/logstash/pipeline
xpack.monitoring.elasticsearch.url: http://elasticsearch:9200
xpack.monitoring.enabled: true
